services:
  desktop:
    build: .
    container_name: firefox-with-applets-vnc
    restart: always

    # ports
    ports:
      - "5901:5901"  # VNC
      - "6901:6901"  # noVNC web
      - "6080:6080"
    shm_size: "2gb"
