services:
  desktop:
    build: .
    container_name: firefox-with-applets-vnc
    restart: always

    # ports
    ports:
      - "5900:5900"  # VNC
      - "6080:6080"  # noVNC web
    shm_size: "2gb"
